name: imagewidget
description: Fighttech Flutter Image Widget
version: 0.0.25
homepage: https://tech.fighttech.vn

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5
  extended_image: ^6.3.1
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1